### PR TITLE
Issue 32

### PR DESCRIPTION
**Pull request by jaapjansma**
See issue #32

### CODE REVIEW

**Comment by systopia** [comment]
@jaapjansma Could you resolve the conflicts herer?

**Comment by jaapjansma** [comment]
@systopia I have just resolved the conflicts.

**Comment by systopia** [comment]
@jaapjansma great, thanks

**Comment by jaapjansma** [comment]
@systopia Is it possible to create a new release?

**Comment by systopia** [comment]
I have some other things (e.g. #28) I'd like to include. Or I could do a ``0.6.x``, what do you prefer?

**Comment by jaapjansma** [comment]
@systopia I prefer a 0.6.x then, because Velt can then test with a generic version of this extension.

**Pull request merged**
