### PR TITLE
Update membership end date when a membership payment is added

### PR DESCRIPTION
**Pull request by jaapjansma**
See issue #18

### CODE REVIEW

**Comment by systopia** [comment]
@jaapjansma I'll have a look at this when ``0.5 `` is out, ok? Cheers!

**Comment by jaapjansma** [comment]
That is fine. Do you have a clue when 0.5 comes out, roughly?

**Comment by systopia** [comment]
> That is fine. Do you have a clue when 0.5 comes out, roughly?

Soon, if @thomst can confirm that it all works fine now...

**Comment by jaapjansma** [comment]
@systopia I have added another commit as CiviCRM seems to have weird behaviour: if you set a pending contribution to completed through the UI the membership gets renewed. If you set a In Progress contribution to completed the membership does not get renewed. And if you set a contribution to completed through the api it does not get renewed either.

**Comment by systopia** [comment]
> @systopia I have added another commit as CiviCRM seems to have weird behaviour...

Yes, that's what #14 is about. Maybe we can have a chat next week to see what our options are...

**Comment by jaapjansma** [comment]
I have added a another popup to replace the date in the status message after completing a membership contribution from within the UI.

**Comment by jaapjansma** [comment]
@systopia a chat next week is fine. I can do everyday except monday morning and thursday afternoon

**Comment by jaapjansma** [comment]
Thanks.

**Comment by systopia** [comment]
Thank _you_ :)

**Pull request merged**
