### PR TITLE
Fixing cid + offset

### PR DESCRIPTION
**Pull request by epdmack**
Found the bug mentioned in #57. 
It was an incorrectly used variable and the generator should now work again at that point.

### CODE REVIEW

**Comment by bjendres** [comment]
Thanks @epdmack, great find. I can't believe this was in there for so long...

**Comment by bjendres** [comment]
I have released this as ``org.project60.membership-0.7-beta1``. 

@epdmack could you report back if everything else works well on your end, so we can release ``0.7``?

**Comment by epdmack** [comment]
@bjendres yes, everything else works well for me, you can do the release

**Comment by bjendres** [comment]
Thanks. I'll wait for some more feedback from other people and will release next week.

**Pull request merged**
